<%@ page import="sys.constants.AbroadConstants" %>
<%@ page language="java" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<c:set value="${_pMap['abroadContactUseSign']=='true'}" var="_p_abroadContactUseSign"/>

<c:set var="ABROAD_APPLY_SELF_DATE_TYPE_MAP" value="<%=AbroadConstants.ABROAD_APPLY_SELF_DATE_TYPE_MAP%>"/>
<c:set var="ABROAD_PASSPORT_DRAW_TYPE_MAP" value="<%=AbroadConstants.ABROAD_PASSPORT_DRAW_TYPE_MAP%>"/>

<c:set var="ABROAD_PASSPORT_TYPE_KEEP" value="<%=AbroadConstants.ABROAD_PASSPORT_TYPE_KEEP%>"/>
<c:set var="ABROAD_PASSPORT_TYPE_LOST" value="<%=AbroadConstants.ABROAD_PASSPORT_TYPE_LOST%>"/>
<c:set var="ABROAD_PASSPORT_TYPE_CANCEL" value="<%=AbroadConstants.ABROAD_PASSPORT_TYPE_CANCEL%>"/>
<c:set var="ABROAD_PASSPORT_TYPE_MAP" value="<%=AbroadConstants.ABROAD_PASSPORT_TYPE_MAP%>"/>

<c:set var="ABROAD_PASSPORT_CANCEL_TYPE_ABOLISH" value="<%=AbroadConstants.ABROAD_PASSPORT_CANCEL_TYPE_ABOLISH%>"/>
<c:set var="ABROAD_PASSPORT_CANCEL_TYPE_OTHER" value="<%=AbroadConstants.ABROAD_PASSPORT_CANCEL_TYPE_OTHER%>"/>
<c:set var="ABROAD_PASSPORT_CANCEL_TYPE_MAP" value="<%=AbroadConstants.ABROAD_PASSPORT_CANCEL_TYPE_MAP%>"/>

<c:set var="ABROAD_PASSPORT_LOST_TYPE_TRANSFER" value="<%=AbroadConstants.ABROAD_PASSPORT_LOST_TYPE_TRANSFER%>"/>

<c:set var="ABROAD_PASSPORT_DRAW_USE_TYPE_MAP" value="<%=AbroadConstants.ABROAD_PASSPORT_DRAW_USE_TYPE_MAP%>"/>

<c:set var="ABROAD_PASSPORT_DRAW_TYPE_SELF" value="<%=AbroadConstants.ABROAD_PASSPORT_DRAW_TYPE_SELF%>"/>
<c:set var="ABROAD_PASSPORT_DRAW_TYPE_TW" value="<%=AbroadConstants.ABROAD_PASSPORT_DRAW_TYPE_TW%>"/>
<c:set var="ABROAD_PASSPORT_DRAW_TYPE_OTHER" value="<%=AbroadConstants.ABROAD_PASSPORT_DRAW_TYPE_OTHER%>"/>
<c:set var="ABROAD_PASSPORT_DRAW_TYPE_LONG_SELF" value="<%=AbroadConstants.ABROAD_PASSPORT_DRAW_TYPE_LONG_SELF%>"/>
<c:set var="ABROAD_PASSPORT_DRAW_TYPE_PUB_SELF" value="<%=AbroadConstants.ABROAD_PASSPORT_DRAW_TYPE_PUB_SELF%>"/>

<c:set var="ABROAD_PASSPORT_DRAW_STATUS_INIT" value="<%=AbroadConstants.ABROAD_PASSPORT_DRAW_STATUS_INIT%>"/>
<c:set var="ABROAD_PASSPORT_DRAW_STATUS_PASS" value="<%=AbroadConstants.ABROAD_PASSPORT_DRAW_STATUS_PASS%>"/>
<c:set var="ABROAD_PASSPORT_DRAW_STATUS_NOT_PASS" value="<%=AbroadConstants.ABROAD_PASSPORT_DRAW_STATUS_NOT_PASS%>"/>
<c:set var="ABROAD_PASSPORT_DRAW_STATUS_MAP" value="<%=AbroadConstants.ABROAD_PASSPORT_DRAW_STATUS_MAP%>"/>

<c:set var="ABROAD_PASSPORT_DRAW_DRAW_STATUS_UNDRAW" value="<%=AbroadConstants.ABROAD_PASSPORT_DRAW_DRAW_STATUS_UNDRAW%>"/>
<c:set var="ABROAD_PASSPORT_DRAW_DRAW_STATUS_DRAW" value="<%=AbroadConstants.ABROAD_PASSPORT_DRAW_DRAW_STATUS_DRAW%>"/>
<c:set var="ABROAD_PASSPORT_DRAW_DRAW_STATUS_RETURN" value="<%=AbroadConstants.ABROAD_PASSPORT_DRAW_DRAW_STATUS_RETURN%>"/>
<c:set var="ABROAD_PASSPORT_DRAW_DRAW_STATUS_ABOLISH" value="<%=AbroadConstants.ABROAD_PASSPORT_DRAW_DRAW_STATUS_ABOLISH%>"/>
<c:set var="ABROAD_PASSPORT_DRAW_DRAW_STATUS_MAP" value="<%=AbroadConstants.ABROAD_PASSPORT_DRAW_DRAW_STATUS_MAP%>"/>

<c:set var="ABROAD_PASSPORT_DRAW_USEPASSPORT_REFUSE_RETURN" value="<%=AbroadConstants.ABROAD_PASSPORT_DRAW_USEPASSPORT_REFUSE_RETURN%>"/>

<c:set var="ABROAD_PASSPORT_APPLY_STATUS_INIT" value="<%=AbroadConstants.ABROAD_PASSPORT_APPLY_STATUS_INIT%>"/>
<c:set var="ABROAD_PASSPORT_APPLY_STATUS_PASS" value="<%=AbroadConstants.ABROAD_PASSPORT_APPLY_STATUS_PASS%>"/>
<c:set var="ABROAD_PASSPORT_APPLY_STATUS_NOT_PASS" value="<%=AbroadConstants.ABROAD_PASSPORT_APPLY_STATUS_NOT_PASS%>"/>
<c:set var="ABROAD_PASSPORT_APPLY_STATUS_MAP" value="<%=AbroadConstants.ABROAD_PASSPORT_APPLY_STATUS_MAP%>"/>

<c:set var="ABROAD_TAIWAN_RECORD_HANDLE_TYPE_OW" value="<%=AbroadConstants.ABROAD_TAIWAN_RECORD_HANDLE_TYPE_OW%>"/>
<c:set var="ABROAD_TAIWAN_RECORD_HANDLE_TYPE_OFFICE" value="<%=AbroadConstants.ABROAD_TAIWAN_RECORD_HANDLE_TYPE_OFFICE%>"/>
<c:set var="ABROAD_TAIWAN_RECORD_HANDLE_TYPE_MAP" value="<%=AbroadConstants.ABROAD_TAIWAN_RECORD_HANDLE_TYPE_MAP%>"/>

<c:set var="ABROAD_APPROVER_TYPE_UNIT_PRINCIPAL" value="<%=AbroadConstants.ABROAD_APPROVER_TYPE_UNIT_PRINCIPAL%>"/>
<c:set var="ABROAD_APPROVER_TYPE_LEADER" value="<%=AbroadConstants.ABROAD_APPROVER_TYPE_LEADER%>"/>
<c:set var="ABROAD_APPROVER_TYPE_MAP" value="<%=AbroadConstants.ABROAD_APPROVER_TYPE_MAP%>"/>