<%@ page import="sys.constants.ModifyConstants" %>
<%@ page language="java" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<c:set var="MODIFY_BASE_ITEM_TYPE_STRING" value="<%=ModifyConstants.MODIFY_BASE_ITEM_TYPE_STRING%>"/>
<c:set var="MODIFY_BASE_ITEM_TYPE_INT" value="<%=ModifyConstants.MODIFY_BASE_ITEM_TYPE_INT%>"/>
<c:set var="MODIFY_BASE_ITEM_TYPE_DATE" value="<%=ModifyConstants.MODIFY_BASE_ITEM_TYPE_DATE%>"/>
<c:set var="MODIFY_BASE_ITEM_TYPE_IMAGE" value="<%=ModifyConstants.MODIFY_BASE_ITEM_TYPE_IMAGE%>"/>
<c:set var="MODIFY_BASE_ITEM_TYPE_MAP" value="<%=ModifyConstants.MODIFY_BASE_ITEM_TYPE_MAP%>"/>

<c:set var="MODIFY_BASE_APPLY_STATUS_APPLY" value="<%=ModifyConstants.MODIFY_BASE_APPLY_STATUS_APPLY%>"/>
<c:set var="MODIFY_BASE_APPLY_STATUS_DELETE" value="<%=ModifyConstants.MODIFY_BASE_APPLY_STATUS_DELETE%>"/>
<c:set var="MODIFY_BASE_APPLY_STATUS_ALL_CHECK" value="<%=ModifyConstants.MODIFY_BASE_APPLY_STATUS_ALL_CHECK%>"/>

<c:set var="MODIFY_BASE_ITEM_STATUS_MAP" value="<%=ModifyConstants.MODIFY_BASE_ITEM_STATUS_MAP%>"/>

<c:set var="MODIFY_TABLE_APPLY_STATUS_APPLY" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_STATUS_APPLY%>"/>
<c:set var="MODIFY_TABLE_APPLY_STATUS_MAP" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_STATUS_MAP%>"/>

<c:set var="MODIFY_TABLE_APPLY_MODULE_CADRE_EDU" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_MODULE_CADRE_EDU%>"/>
<c:set var="MODIFY_TABLE_APPLY_MODULE_CADRE_WORK" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_MODULE_CADRE_WORK%>"/>
<c:set var="MODIFY_TABLE_APPLY_MODULE_CADRE_BOOK" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_MODULE_CADRE_BOOK%>"/>
<c:set var="MODIFY_TABLE_APPLY_MODULE_CADRE_COMPANY" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_MODULE_CADRE_COMPANY%>"/>
<c:set var="MODIFY_TABLE_APPLY_MODULE_CADRE_COURSE" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_MODULE_CADRE_COURSE%>"/>
<c:set var="MODIFY_TABLE_APPLY_MODULE_CADRE_PAPER" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_MODULE_CADRE_PAPER%>"/>
<c:set var="MODIFY_TABLE_APPLY_MODULE_CADRE_PARTTIME" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_MODULE_CADRE_PARTTIME%>"/>
<c:set var="MODIFY_TABLE_APPLY_MODULE_CADRE_RESEARCH_IN" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_MODULE_CADRE_RESEARCH_IN%>"/>
<c:set var="MODIFY_TABLE_APPLY_MODULE_CADRE_RESEARCH_DIRECT" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_MODULE_CADRE_RESEARCH_DIRECT%>"/>
<c:set var="MODIFY_TABLE_APPLY_MODULE_CADRE_REWARD_TEACH" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_MODULE_CADRE_REWARD_TEACH%>"/>
<c:set var="MODIFY_TABLE_APPLY_MODULE_CADRE_REWARD_RESEARCH" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_MODULE_CADRE_REWARD_RESEARCH%>"/>
<c:set var="MODIFY_TABLE_APPLY_MODULE_CADRE_REWARD_OTHER" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_MODULE_CADRE_REWARD_OTHER%>"/>
<c:set var="MODIFY_TABLE_APPLY_MODULE_CADRE_TRAIN" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_MODULE_CADRE_TRAIN%>"/>

<c:set var="MODIFY_TABLE_APPLY_MODULE_CADRE_POSTPRO" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_MODULE_CADRE_POSTPRO%>"/>
<c:set var="MODIFY_TABLE_APPLY_MODULE_CADRE_POSTADMIN" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_MODULE_CADRE_POSTADMIN%>"/>
<c:set var="MODIFY_TABLE_APPLY_MODULE_CADRE_POSTWORK" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_MODULE_CADRE_POSTWORK%>"/>
<c:set var="MODIFY_TABLE_APPLY_MODULE_CADRE_FAMILY" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_MODULE_CADRE_FAMILY%>"/>
<c:set var="MODIFY_TABLE_APPLY_MODULE_CADRE_FAMILYABROAD" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_MODULE_CADRE_FAMILYABROAD%>"/>

<c:set var="MODIFY_TABLE_APPLY_MODULE_MAP" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_MODULE_MAP%>"/>

<c:set var="MODIFY_TABLE_APPLY_TYPE_MODIFY" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_TYPE_MODIFY%>"/>
<c:set var="MODIFY_TABLE_APPLY_TYPE_DELETE" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_TYPE_DELETE%>"/>
<c:set var="MODIFY_TABLE_APPLY_TYPE_MAP" value="<%=ModifyConstants.MODIFY_TABLE_APPLY_TYPE_MAP%>"/>